# Generated by Django 2.0.1 on 2018-02-26 20:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('title', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('contentText', models.TextField()),
                ('author', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=1000)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('comment', models.TextField()),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('blog', models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='Blogs.BlogPost')),
            ],
        ),
    ]
