# Generated by Django 2.0.1 on 2018-02-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='edit_date',
            field=models.DateField(null=True),
        ),
    ]
