# Generated by Django 2.0.1 on 2018-02-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_blogpost_edit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
